# docker-compose.yml
version: '3.8'

services:
  # 1. Our custom Go API Gateway Service [Ini container 1]
  go-api-gateway:
    build: ./core/api-gateway # Build from the new gateway directory
    container_name: go-api-gateway
    ports:
      - "80:8080" # Map host port 80 to container port 8080
    restart: always
    depends_on:
      - go-auth-service # Ensure the auth service is running before the gateway starts

  # 2. Go API Service  [Ini container 2]
  go-auth-service:
    build: ./services/auth-go
    container_name: golang-auth-service
    # Note: We no longer expose this port to the outside world.
    # It is only accessible from other containers on the internal network.
    expose:
      - "8080"
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-user}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_NAME: ${DB_NAME:-travelezia}
    depends_on:
      - db

  # 3. PostgreSQL Database Service  [Ini container khusus DB]
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-travelezia}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./core/database/migrations:/docker-entrypoint-initdb.d
    container_name: postgres-db
    restart: always

volumes:
  postgres_data:
